[build]
target = "x86_64-unknown-steelmind_os.json"

# rustflags = [
#     "-C", "link-arg=-z",
#     "-C", "link-arg=nostart-stop-gc",
# ]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]